// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package examples

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/invopop/popui.go"
	"github.com/invopop/popui.go/props"
)

func TablePaginationAlpineExample() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"{\n\t\t\tcurrentPage: 1,\n\t\t\ttotalPages: 260,\n\t\t\ttotalItems: 25991,\n\t\t\trowsPerPage: 100,\n\t\t\titemsLabel: 'invoices',\n\t\t\tgoToPage(page) {\n\t\t\t\tconst pageNum = parseInt(page);\n\t\t\t\tif (pageNum >= 1 && pageNum <= this.totalPages) {\n\t\t\t\t\tthis.currentPage = pageNum;\n\t\t\t\t\t// Here you would typically fetch new data from your API\n\t\t\t\t\tconsole.log('Navigating to page:', pageNum);\n\t\t\t\t}\n\t\t\t},\n\t\t\tchangeRowsPerPage(value) {\n\t\t\t\tthis.rowsPerPage = parseInt(value);\n\t\t\t\tthis.currentPage = 1;\n\t\t\t\t// Recalculate total pages based on new rows per page\n\t\t\t\tconsole.log('Changed rows per page to:', value);\n\t\t\t}\n\t\t}\" class=\"border border-border rounded-lg overflow-hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<thead><tr><th>Invoice ID</th><th>Customer</th><th>Amount</th><th>Status</th></tr></thead> <tbody><tr><td>INV-001</td><td>Acme Corp</td><td>$1,234.56</td><td>Paid</td></tr><tr><td>INV-002</td><td>Tech Solutions</td><td>$987.65</td><td>Pending</td></tr><tr><td>INV-003</td><td>Global Inc</td><td>$2,345.67</td><td>Paid</td></tr></tbody>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = popui.Table().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = popui.TablePagination(props.TablePagination{
			CurrentPage:        1,
			TotalPages:         260,
			TotalItems:         25991,
			RowsPerPage:        100,
			RowsPerPageOptions: []int{10, 25, 50, 100, 250},
			ShowRowsPerPage:    true,
			ItemsLabel:         "invoices",
			FirstPageURL:       "#",
			PrevPageURL:        "#",
			NextPageURL:        "#",
			LastPageURL:        "#",
			Elements: props.TablePaginationElements{
				First: templ.Attributes{
					"@click.prevent":       "goToPage(1)",
					"x-bind:data-disabled": "currentPage === 1",
				},
				Prev: templ.Attributes{
					"@click.prevent":       "goToPage(currentPage - 1)",
					"x-bind:data-disabled": "currentPage === 1",
				},
				Next: templ.Attributes{
					"@click.prevent":       "goToPage(currentPage + 1)",
					"x-bind:data-disabled": "currentPage === totalPages",
				},
				Last: templ.Attributes{
					"@click.prevent":       "goToPage(totalPages)",
					"x-bind:data-disabled": "currentPage === totalPages",
				},
				Page: templ.Attributes{
					"x-model.number": "currentPage",
					"@input":         "goToPage($event.target.value)",
				},
				Select: templ.Attributes{
					"x-model": "rowsPerPage",
					"@change": "changeRowsPerPage($event.target.value)",
				},
				TotalPages: templ.Attributes{
					"x-text": "totalPages",
				},
				TotalItems: templ.Attributes{
					"x-text": "`${totalItems} ${itemsLabel}`",
				},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
