// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
// Package components provides documentation pages for PopUI components.

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	_ "embed"
	"github.com/invopop/popui.go/internal/docs/examples"
	"github.com/invopop/popui.go/internal/docs/modules"
)

func Card() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = examples.CardExample().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = modules.Example(modules.ExampleProps{
			Code: examples.LoadExample("card.templ"),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = examples.CardWithHeaderExample().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = modules.Example(modules.ExampleProps{
			Title:       "With Header",
			Description: "Cards can include a header with avatar, title, and subtitle using the CardHeader component.",
			Code:        examples.LoadExample("card_with_header.templ"),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = examples.CardDisabledExample().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = modules.Example(modules.ExampleProps{
			Title:       "Disabled State",
			Description: "Cards can be disabled to indicate they are not interactive.",
			Code:        examples.LoadExample("card_disabled.templ"),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = examples.CardAsLinkExample().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = modules.Example(modules.ExampleProps{
			Title:       "As Link",
			Description: "Cards can act as clickable links by providing an Href prop, rendering as an anchor element.",
			Code:        examples.LoadExample("card_as_link.templ"),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = examples.CardProgressBarExample().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = modules.Example(modules.ExampleProps{
			Title:       "Progress Bar",
			Description: "CardProgressBar displays progress with a visual indicator and optional counter.",
			Code:        examples.LoadExample("card_progress_bar.templ"),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = examples.CardDashboardExample().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = modules.Example(modules.ExampleProps{
			Title:       "Dashboard",
			Description: "CardDashboard displays multiple metrics in a grid layout.",
			Code:        examples.LoadExample("card_dashboard.templ"),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var7), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var8 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = examples.CardFileExample().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = modules.Example(modules.ExampleProps{
			Title:       "File Card",
			Description: "CardFile provides a container for displaying file information.",
			Code:        examples.LoadExample("card_file.templ"),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var8), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var9 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = modules.APITable(modules.APITableProps{
				Title:       "Card",
				Description: "Main container component for displaying content in a bordered box.",
				Items: []modules.APITableItem{
					{Name: "ID", Type: "string", Default: "", Description: "Unique identifier for the card element"},
					{Name: "Class", Type: "string", Default: "", Description: "Additional CSS classes to merge with card styles"},
					{Name: "Attributes", Type: "templ.Attributes", Default: "", Description: "Additional HTML attributes (data-*, aria-*, etc.)"},
					{Name: "Href", Type: "templ.SafeURL", Default: "", Description: "URL to navigate to when card is clicked (renders as anchor)"},
					{Name: "Disabled", Type: "bool", Default: "false", Description: "Disables the card and applies disabled styling"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = modules.APITable(modules.APITableProps{
				Title:       "CardContent",
				Description: "Content container for cards with consistent padding and text styling.",
				Items: []modules.APITableItem{
					{Name: "ID", Type: "string", Default: "", Description: "Unique identifier for the content element"},
					{Name: "Class", Type: "string", Default: "", Description: "Additional CSS classes to merge with content styles"},
					{Name: "Attributes", Type: "templ.Attributes", Default: "", Description: "Additional HTML attributes"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = modules.APITable(modules.APITableProps{
				Title:       "CardHeader",
				Description: "Header component for cards. Expects Avatar or other content as children.",
				Items: []modules.APITableItem{
					{Name: "ID", Type: "string", Default: "", Description: "Unique identifier for the header element"},
					{Name: "Class", Type: "string", Default: "", Description: "Additional CSS classes to merge with header styles"},
					{Name: "Attributes", Type: "templ.Attributes", Default: "", Description: "Additional HTML attributes"},
					{Name: "Title", Type: "string", Default: "", Description: "Main title text"},
					{Name: "Subtitle", Type: "string", Default: "", Description: "Secondary subtitle text"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = modules.APITable(modules.APITableProps{
				Title:       "CardProgressBar",
				Description: "Displays progress with a visual bar and optional counter.",
				Items: []modules.APITableItem{
					{Name: "ID", Type: "string", Default: "", Description: "Unique identifier for the progress bar element"},
					{Name: "Class", Type: "string", Default: "", Description: "Additional CSS classes to merge with progress bar styles"},
					{Name: "Attributes", Type: "templ.Attributes", Default: "", Description: "Additional HTML attributes"},
					{Name: "Title", Type: "string", Default: "", Description: "Main title text"},
					{Name: "Subtitle", Type: "string", Default: "", Description: "Secondary subtitle text"},
					{Name: "Current", Type: "int64", Default: "0", Description: "Current progress value"},
					{Name: "Total", Type: "int64", Default: "0", Description: "Total/maximum value for progress"},
					{Name: "HideCounter", Type: "bool", Default: "false", Description: "Hides the numeric counter display"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = modules.APITable(modules.APITableProps{
				Title:       "CardDashboard",
				Description: "Grid layout for displaying multiple metrics. Expects CardDashboardItem components as children.",
				Items: []modules.APITableItem{
					{Name: "ID", Type: "string", Default: "", Description: "Unique identifier for the dashboard element"},
					{Name: "Class", Type: "string", Default: "", Description: "Additional CSS classes to merge with dashboard styles"},
					{Name: "Attributes", Type: "templ.Attributes", Default: "", Description: "Additional HTML attributes"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = modules.APITable(modules.APITableProps{
				Title:       "CardDashboardItem",
				Description: "Individual metric item for CardDashboard.",
				Items: []modules.APITableItem{
					{Name: "ID", Type: "string", Default: "", Description: "Unique identifier for the item element"},
					{Name: "Class", Type: "string", Default: "", Description: "Additional CSS classes to merge with item styles"},
					{Name: "Attributes", Type: "templ.Attributes", Default: "", Description: "Additional HTML attributes"},
					{Name: "Label", Type: "string", Default: "", Description: "Label text for the metric"},
					{Name: "Value", Type: "string", Default: "", Description: "Value text for the metric"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = modules.APITable(modules.APITableProps{
				Title:       "CardFile",
				Description: "Container for displaying file information. Expects CardFileInfo and action buttons as children.",
				Items: []modules.APITableItem{
					{Name: "ID", Type: "string", Default: "", Description: "Unique identifier for the file card element"},
					{Name: "Class", Type: "string", Default: "", Description: "Additional CSS classes to merge with file card styles"},
					{Name: "Attributes", Type: "templ.Attributes", Default: "", Description: "Additional HTML attributes"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = modules.APITable(modules.APITableProps{
				Title:       "CardFileInfo",
				Description: "Structured layout for file information within CardFile (icon, name, etc.).",
				Items: []modules.APITableItem{
					{Name: "ID", Type: "string", Default: "", Description: "Unique identifier for the file info element"},
					{Name: "Class", Type: "string", Default: "", Description: "Additional CSS classes to merge with file info styles"},
					{Name: "Attributes", Type: "templ.Attributes", Default: "", Description: "Additional HTML attributes"},
					{Name: "Label", Type: "string", Default: "", Description: "File name or label text to display"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = modules.Section("API Reference", "api").Render(templ.WithChildren(ctx, templ_7745c5c3_Var9), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
